### ISSUE TITLE
拉取镜像时出现 401错误

### ISSUE THREAD

**Issue by pospos369** [whyun-pages/docker-registry#3]
2024 年 09 月 12 日auth.docker.io 被墙，反代了官方仓库的镜像源拉取镜像时出现 401错误

**Comment by yunnysunny** [comment]
请尝试配置环境变量 `SELF_AUTH` ，并将其设置为 `true`，参见文档 https://github.com/whyun-pages/docker-registry?tab=readme-ov-file#self_auth

**Comment by pospos369** [comment]
> 请尝试配置环境变量 `SELF_AUTH` ，并将其设置为 `true`，参见文档 https://github.com/whyun-pages/docker-registry?tab=readme-ov-file#self_auth
配置变量后重新部署问题解决，多谢多谢！
